### ISSUE TITLE
Create Github Actions workflow

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#10]
Create Github Actions workflow for project set-up and build using JAR, and Docker on GitHub Actions.

**Comment by Alex180504** [comment]
USER STORY:
As a development team member,
I want a Github Actions Workflow set up,
so that i can perform buid and deployment test more easily
ACCEPTANCE CRITERIA:
Given IDE window active
When commits pushed to GitHub
Then aoutomated build & deployment workflow is performed
