### ISSUE TITLE
Country Report by region

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#18]
Write an SQL query and Java function to return such information:
"All the countries in a region organised by largest population to smallest"
The function should accept such parameters:
Region
The query should return such information:
Code
Name
Continent
Region
Population
Capital

**Comment by Alex180504** [comment]
As a user, I want to generate a report on all countries in the region specified by me, organized by their population in descending order so that I can quickly view the regional population distribution.
