### ISSUE TITLE
Country Report for region(limit N)

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#21]
Write an SQL query and Java function to return such information:
"The top N populated countries in a region where N is provided by the user"
The function should accept such parameters:
N
Region
The query should return such information:
Code
Name
Continent
Region
Population
Capital

**Comment by Alex180504** [comment]
As a user, I want to generate a report on the top N populated countries in the region specified by me, where N is a value provided by me so that I can quickly find information on the most populated countries in the region.
