### ISSUE TITLE
City Report for country

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#25]
Write an SQL query and Java function to return such information:
"All the cities in a country organised by largest population to smallest"
The function should accept such arguments:
**Country**
The query should return such information:
**Name**
**Country**
**District**
**Population**

**Comment by sneri12pic** [comment]
As a user, I want to generate a report on all cities in the country specified by me, organized by their population in descending order so that I can quickly view the cities population distribution.
