### ISSUE TITLE
City Report for world(limit N)

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#27]
Write an SQL query and Java function to return such information:
"The top N populated cities in the world where N is provided by the user"
The function should accept such arguments:
**N**
The query should return such information:
**Name**
**Country**
**District**
**Population**

**Comment by sneri12pic** [comment]
As a user, I want to generate a report  limited by number of cities I want to see in the world specified by me, organized by their population in descending order so that I can quickly view the cities population distribution.
