### ISSUE TITLE
Capital City Report by continent

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#38]
Write an SQL query and Java function to return such information:
"All the capital cities in a continent organised by largest population to smallest."
The function should accept such arguments:
**Continent**
The query should return such information:
**Name**
**Country**
**Population**

**Comment by sneri12pic** [comment]
As a user, I want to generate a report on all Capital Cities in the continent specified by me, organized by their population in descending order so that I can quickly view the cities population distribution.
