### ISSUE TITLE
Capital City Report by region(limit N)

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#42]
Write an SQL query and Java function to return such information:
"The top N populated capital cities in a region where N is provided by the use"
The function should accept such arguments:
**N**
**Region**
The query should return such information:
**Name**
**Country**
**Population**

**Comment by sneri12pic** [comment]
As a user, I want to generate a report  limited by number of Capital Cities I want to see in the region specified by me, organized by their population in descending order so that I can quickly view the cities population distribution.
