### ISSUE TITLE
Add JAR building to Maven

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#8]
Make so it builds to self-contained JAR with Maven

**Comment by Drakon4ik-Coder** [comment]
Test

**Comment by Alex180504** [comment]
USER STORY:
As a user
I want the project to have an accecible binary
so that I can run it my machine more easily
ACCEPTANCE CRITERIA:
Given JAR directory open
When JAR file double clicked
Then program runs
